`ifndef PRIM_FIFO_ASSERT_SVH
`define PRIM_FIFO_ASSERT_SVH

// Use PRIM_COUNT_ERROR_TRIGGER_ALERT appropriately to check that the three prim_counts generated by
// a prim_fifo_sync with depth at least two do indeed generate an alert if they detect an error.
`define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT(NAME_, HIER_, ALERT_, GATE_, MAX_CYCLES_) \
  `ASSERT_PRIM_COUNT_ERROR_TRIGGER_ALERT(``NAME_``WptrCheck_A,                               \
                                         HIER_.gen_normal_fifo.u_fifo_cnt.gen_secure_ptrs.u_wptr, \
                                         ALERT_,                                             \
                                         GATE_,                                              \
                                         MAX_CYCLES_)                                        \
  `ASSERT_PRIM_COUNT_ERROR_TRIGGER_ALERT(``NAME_``RptrCheck_A,                               \
                                         HIER_.gen_normal_fifo.u_fifo_cnt.gen_secure_ptrs.u_rptr, \
                                         ALERT_,                                             \
                                         GATE_,                                              \
                                         MAX_CYCLES_)

// Assertion for depth-1 FIFOs
`define ASSERT_PRIM_FIFO_SYNC_ERROR_TRIGGERS_ALERT1(NAME_, HIER_, ALERT_, GATE_, MAX_CYCLES_) \
  `ASSERT_ERROR_TRIGGER_ALERT(``NAME_``FullCheck_A,                                           \
                              HIER_,                                                          \
                              ALERT_,                                                         \
                              GATE_,                                                          \
                              MAX_CYCLES_,                                                    \
                              err_o)

`endif // PRIM_FIFO_ASSERT_SVH
