// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package uart_reg_pkg;

  // Param list
  parameter int RxFifoDepth = 64;
  parameter int TxFifoDepth = 32;
  parameter int NumAlerts = 1;

  // Address widths within the block
  parameter int BlockAw = 6;

  // Number of registers for every interface
  parameter int NumRegs = 13;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
    } tx_empty;
    struct packed {
      logic        q;
    } rx_parity_err;
    struct packed {
      logic        q;
    } rx_timeout;
    struct packed {
      logic        q;
    } rx_break_err;
    struct packed {
      logic        q;
    } rx_frame_err;
    struct packed {
      logic        q;
    } rx_overflow;
    struct packed {
      logic        q;
    } tx_done;
    struct packed {
      logic        q;
    } rx_watermark;
    struct packed {
      logic        q;
    } tx_watermark;
  } uart_reg2hw_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } tx_empty;
    struct packed {
      logic        q;
    } rx_parity_err;
    struct packed {
      logic        q;
    } rx_timeout;
    struct packed {
      logic        q;
    } rx_break_err;
    struct packed {
      logic        q;
    } rx_frame_err;
    struct packed {
      logic        q;
    } rx_overflow;
    struct packed {
      logic        q;
    } tx_done;
    struct packed {
      logic        q;
    } rx_watermark;
    struct packed {
      logic        q;
    } tx_watermark;
  } uart_reg2hw_intr_enable_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } tx_empty;
    struct packed {
      logic        q;
      logic        qe;
    } rx_parity_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_timeout;
    struct packed {
      logic        q;
      logic        qe;
    } rx_break_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_frame_err;
    struct packed {
      logic        q;
      logic        qe;
    } rx_overflow;
    struct packed {
      logic        q;
      logic        qe;
    } tx_done;
    struct packed {
      logic        q;
      logic        qe;
    } rx_watermark;
    struct packed {
      logic        q;
      logic        qe;
    } tx_watermark;
  } uart_reg2hw_intr_test_reg_t;

  typedef struct packed {
    logic        q;
    logic        qe;
  } uart_reg2hw_alert_test_reg_t;

// Control Register start
  typedef struct packed {
    struct packed {
      logic [15:0] q;
    } nco;
    struct packed {
      logic [1:0]  q;
    } rxblvl;
    struct packed {
      logic        q;
    } parity_odd;
    struct packed {
      logic        q;
    } parity_en;
    struct packed {
      logic        q;
    } llpbk;
    struct packed {
      logic        q;
    } slpbk;
    struct packed {
      logic        q;
    } nf;
    struct packed {
      logic        q;
    } rx;
    struct packed {
      logic        q;
    } tx;
  } uart_reg2hw_ctrl_reg_t;
// Control Register end

  typedef struct packed {
    struct packed {
      logic        q;
      logic        re;
    } rxempty;
    struct packed {
      logic        q;
      logic        re;
    } rxidle;
    struct packed {
      logic        q;
      logic        re;
    } txidle;
    struct packed {
      logic        q;
      logic        re;
    } txempty;
    struct packed {
      logic        q;
      logic        re;
    } rxfull;
    struct packed {
      logic        q;
      logic        re;
    } txfull;
  } uart_reg2hw_status_reg_t;

// start
// Read Data Register
  typedef struct packed {
    logic [7:0]  q; // do not touch
    logic        re; // touch to pop byte frm fifo
  } uart_reg2hw_rdata_reg_t;

// Write Data Register
  typedef struct packed {
    logic [7:0]  q;
    logic        qe;
  } uart_reg2hw_wdata_reg_t;
//end

  typedef struct packed {
    struct packed {
      logic [2:0]  q;
      logic        qe;
    } txilvl;
    struct packed {
      logic [2:0]  q;
      logic        qe;
    } rxilvl;
    struct packed {
      logic        q;
      logic        qe;
    } txrst;
    struct packed {
      logic        q;
      logic        qe;
    } rxrst;
  } uart_reg2hw_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } txval;
    struct packed {
      logic        q;
    } txen;
  } uart_reg2hw_ovrd_reg_t;

  typedef struct packed {
    struct packed {
      logic        q;
    } en;
    struct packed {
      logic [23:0] q;
    } val;
  } uart_reg2hw_timeout_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } tx_empty;
    struct packed {
      logic        d;
      logic        de;
    } rx_parity_err;
    struct packed {
      logic        d;
      logic        de;
    } rx_timeout;
    struct packed {
      logic        d;
      logic        de;
    } rx_break_err;
    struct packed {
      logic        d;
      logic        de;
    } rx_frame_err;
    struct packed {
      logic        d;
      logic        de;
    } rx_overflow;
    struct packed {
      logic        d;
      logic        de;
    } tx_done;
    struct packed {
      logic        d;
      logic        de;
    } rx_watermark;
    struct packed {
      logic        d;	//set value
      logic        de;	//apply value(1) or not(0)
    } tx_watermark;
  } uart_hw2reg_intr_state_reg_t;

  typedef struct packed {
    struct packed {
      logic        d;
    } rxempty;
    struct packed {
      logic        d;
    } rxidle;
    struct packed {
      logic        d;
    } txidle;
    struct packed {
      logic        d;
    } txempty;
    struct packed {
      logic        d;
    } rxfull;
    struct packed {
      logic        d;
    } txfull;
  } uart_hw2reg_status_reg_t;

  typedef struct packed {
    logic [7:0]  d;
  } uart_hw2reg_rdata_reg_t;

  typedef struct packed {
    struct packed {
      logic [2:0]  d;
      logic        de;
    } txilvl;
    struct packed {
      logic [2:0]  d;
      logic        de;
    } rxilvl;
  } uart_hw2reg_fifo_ctrl_reg_t;

  typedef struct packed {
    struct packed {
      logic [7:0]  d;
    } rxlvl;
    struct packed {
      logic [7:0]  d;
    } txlvl;
  } uart_hw2reg_fifo_status_reg_t;

  typedef struct packed {
    logic [15:0] d;
  } uart_hw2reg_val_reg_t;


	// IMPORTANT
  // Register -> HW type
  typedef struct packed {
    uart_reg2hw_intr_state_reg_t intr_state; // [131:123]
    uart_reg2hw_intr_enable_reg_t intr_enable; // [122:114]
    uart_reg2hw_intr_test_reg_t intr_test; // [113:96]
    uart_reg2hw_alert_test_reg_t alert_test; // [95:94]
    uart_reg2hw_ctrl_reg_t ctrl; // [93:69]
    uart_reg2hw_status_reg_t status; // [68:57]
    uart_reg2hw_rdata_reg_t rdata; // [56:48]
    uart_reg2hw_wdata_reg_t wdata; // [47:39]
    uart_reg2hw_fifo_ctrl_reg_t fifo_ctrl; // [38:27]
    uart_reg2hw_ovrd_reg_t ovrd; // [26:25]
    uart_reg2hw_timeout_ctrl_reg_t timeout_ctrl; // [24:0]
  } uart_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    uart_hw2reg_intr_state_reg_t intr_state; // [71:54]
    uart_hw2reg_status_reg_t status; // [53:48]
    uart_hw2reg_rdata_reg_t rdata; // [47:40]
    uart_hw2reg_fifo_ctrl_reg_t fifo_ctrl; // [39:32]
    uart_hw2reg_fifo_status_reg_t fifo_status; // [31:16]
    uart_hw2reg_val_reg_t val; // [15:0]
  } uart_hw2reg_t;

  // IMPORTANT ENDS

  
endpackage
